# Generated by Django 4.1.1 on 2022-09-18 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=99)),
            ],
            options={
                'ordering': ['store_name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=99)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.store')),
            ],
            options={
                'ordering': ['expiry_date'],
            },
        ),
    ]
