# Generated by Django 4.1.1 on 2022-09-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_user_store_user_alter_item_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expiry_date',
            field=models.DateField(null=True, verbose_name='Expiry Date'),
        ),
    ]
